### ISSUE TITLE
Strange warning in `elisctl schema upload` help

### ISSUE THREAD

**Issue by pasky** [rossumai/elisctl#10]
The help says
>  WARNING: creation of schema must be carried out with a user from within
>  the organization. The reason is that the schema is automatically attached
>  to the organization of the user, who is creating it.

But the schema just replaces the previous schema in the queues the old schema was attached to, so this is obsolete?

**Comment by KPilnacek** [comment]
At the moment, on API, every schema is directly attached to an organization. It's not obsolete, however, it is valid only for superadmin and only would confuse an ordinary user.

Please take a look at https://github.com/rossumai/elisctl/pull/19, where it is removed.

**Comment by pasky** [comment]
Thanks!
