### ISSUE TITLE
Add tests for windows package

### ISSUE THREAD

**Issue by KPilnacek** [rossumai/elisctl#30]
At the moment the package, once built, must be manually tested.

Start with an automatic integration test that will try to install the package and will run only `elisctl` command (start the interactive shell). This should prove that all python dependencies are OK.

**Comment by evelyn9191** [comment]
The focus of this library will be moved from being primarily a command-line client to a Python API library. We will not be focusing on adding new commands and functions as all of them will be soon added to the Rossum UI or can be done via API directly. So I believe that this issue can be closed. Do you agree?

**Comment by KPilnacek** [comment]
I'd prefer to keep the command line access and would just extract the ElisClient to some other library. However, if that's not the case, we can most probably close this issue as I don't expect any major cross-platform issues.

**Comment by evelyn9191** [comment]
I am closing this issue, then. Let's discuss the final library/command-line tool separation internally.
