### ISSUE TITLE
Schema cannot be downloaded using "schema get -O schema.json 6001"

### ISSUE THREAD

**Issue by martinnedopil** [rossumai/elisctl#32]
Using command schema get -O schema.json 6001 
gives me error:
UnicodeEncodeError: 'charmap' codec can`t encode character '\u010c' in position 244: character maps to <undefined>.
File is created, but empty.

System Windows 7, 64-bit, version 1.0.0., user: siemens-cz-gui-demo@elis.rossum.ai

**Comment by KPilnacek** [comment]
Hello @martinnedopil,

this is an issue with encoding on windows (in Python UTF-8 is used, while windows uses CP-1250). The simplest way how to overcome is to use a flag `--ensure-ascii`.

Then the schema should be downloaded correctly.
With regards
Krystof

**Comment by martinnedopil** [comment]
Working properly.

**Comment by KPilnacek** [comment]
It should work anyway even without the `--ensure-ascii` flag.

**Comment by evelyn9191** [comment]
Got error:
UnicodeEncodeError: 'charmap' codec can't encode character '\u010c' in position 244: character maps to undefined.

When following command was used: 
schema get ID -O schema.json

File was created, but is empty.

Tested on Windows 10 Home, 64-bit, elisctl version 1.1.0, user tobias_demo_cz@elis.rossum.ai

**Comment by KPilnacek** [comment]
Just released a patch for that. Please try the [new version](https://github.com/rossumai/elisctl/releases/tag/v1.1.1)
