### ISSUE TITLE
Send specific User-agent header

### ISSUE THREAD

**Issue by KPilnacek** [rossumai/elisctl#33]
Add header `'User-Agent': python-elisctl/{version}` to https://github.com/rossumai/elisctl/blob/master/elisctl/lib/api_client.py#L93

**Comment by qiq** [comment]
Any reason for including python in the UA string?

**Comment by KPilnacek** [comment]
Just that `requests` have it like that. Although, it's not necessary.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by KPilnacek** [comment]
merged
