### ISSUE TITLE
`elisctl csv get` broken

### ISSUE THREAD

**Issue by pasky** [rossumai/elisctl#4]
It appears to use the CSV connector interface rather than export queue interface, but then it uses the API endpoint URL rather than the CSV connector URL.

(But I'm actually not sure what's the purpose of this subcommand right now. :) )

**Comment by evelyn9191** [comment]
Do we actively use this command @KPilnacek ? Is there a need for this enhancement or can it be closed?

**Comment by KPilnacek** [comment]
I use that command for fetching data from some internal `csv` connector but it's not necessary to keep it. 

The enhancement would be to download a csv from `elis` instead of the connector. Though I have no clue if anybody needs/requests it. If not, we can just remove the subcommand.

**Comment by KPilnacek** [comment]
Actually, removing this command could allow simple removal of `pandas`.
