### ISSUE TITLE
Schema cannot be updated (UnicodeDecodeError)

### ISSUE THREAD

**Issue by evelyn9191** [rossumai/elisctl#48]
Schema cannot be updated when using "schema update ID file.json" when updating schemas in Czech language. Error:
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 1626: character maps to <undefined>

Windows 10 Home, 64-bit, elisctl version 1.1.1.

**Comment by qiq** [comment]
Can you please attach a test schema file that causes the failure?

**Comment by evelyn9191** [comment]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 2856: character maps to undefined. File attached.

[cz_bug.txt](https://github.com/rossumai/elisctl/files/2965760/cz_bug.txt)

**Comment by qiq** [comment]
Thanks @evelyn9191! Cannot reproduce in v2.0.1, so I consider it fixed.
