### ISSUE TITLE
elisctl queue: Add setting user access per queue

### ISSUE THREAD

**Issue by pasky** [rossumai/elisctl#77]
Currently, access settings per queue are controlled only by `user change`. This is very awkward when I create a new queue and would like to grant access to a group of users (who also have access to other queues, that should remain unaffected).

Nice & easy solution would be to allow specifying list of users to access the queue in the `queue change` command.

(Another possibility would be a way to add/remove specific queue for a user instead of always specifying the full list, but that'd still be O(N) instead of O(1) for my usecase.)

**Comment by KPilnacek** [comment]
Implemented in https://github.com/rossumai/elisctl/pull/83
